[build]
  command = "pnpm run build"
  publish = "build"
[build.environment]
  NODE_VERSION = "20"
[[headers]]
  for = "/manifest.webmanifest"
  [headers.values]
    Content-Type = "application/manifest+json"
